repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.2
  hooks:
    # Run the linter.
    - id: ruff-check
- repo: local
  hooks:
    - id: mypy-on-entry
      name: Run mypy on main.py file
      entry: mypy
      language: system
      types: [python]
      args: [--ignore-missing-imports, main.py]
      pass_filenames: false
